# Generated by Django 5.2.8 on 2025-12-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfeed',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawfeed',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawfeed',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
