# Generated by Django 5.0.6 on 2026-01-02 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_ingestion", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("recurring_complaint", "Recurring Complaint"),
                            ("recurring_praise", "Recurring Praise"),
                            ("critical_feedback", "Critical Feedback"),
                            ("product_issue", "Product Issue"),
                            ("product_success", "Product Success"),
                            ("sentiment_trend", "Sentiment Trend"),
                            ("urgent_action", "Urgent Action"),
                        ],
                        help_text="Type of insight",
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Severity/priority level",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Insight title", max_length=255)),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the insight"),
                ),
                (
                    "recommendation",
                    models.TextField(help_text="Actionable recommendations"),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Quantitative metrics supporting the insight",
                    ),
                ),
                (
                    "related_topics",
                    models.JSONField(default=list, help_text="Related topics/keywords"),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="Related product (if applicable)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "sample_feedbacks",
                    models.JSONField(
                        blank=True, default=list, help_text="Sample feedback examples"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this insight is still relevant"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this insight has been addressed",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When insight was resolved", null=True
                    ),
                ),
                (
                    "resolved_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes on how insight was resolved",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When insight was generated"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update time"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        help_text="Entity this insight belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="data_ingestion.businessentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight",
                "verbose_name_plural": "Insights",
                "ordering": ["-created_at", "-severity"],
                "indexes": [
                    models.Index(
                        fields=["entity", "type", "is_active"],
                        name="analysis_in_entity__dd5498_idx",
                    ),
                    models.Index(
                        fields=["severity", "is_active"],
                        name="analysis_in_severit_75a2c3_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analysis_in_created_caed4d_idx"
                    ),
                    models.Index(
                        fields=["is_resolved", "severity"],
                        name="analysis_in_is_reso_f68976_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessedFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        help_text="Overall sentiment",
                        max_length=20,
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        help_text="Confidence score for sentiment (0.0 to 1.0)"
                    ),
                ),
                (
                    "topics",
                    models.JSONField(
                        default=list, help_text="Extracted topics/keywords"
                    ),
                ),
                (
                    "embeddings",
                    models.JSONField(
                        default=list, help_text="Vector embeddings (384-dimensional)"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary", null=True
                    ),
                ),
                (
                    "key_phrases",
                    models.JSONField(
                        default=list, help_text="Important phrases extracted"
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Urgency level",
                        max_length=20,
                    ),
                ),
                (
                    "urgency_score",
                    models.FloatField(
                        default=0.5, help_text="Urgency confidence score (0.0 to 1.0)"
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to process (seconds)",
                        null=True,
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        default="v1.0",
                        help_text="Version of AI models used",
                        max_length=50,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(auto_now_add=True, help_text="When processed"),
                ),
                (
                    "raw_feed",
                    models.OneToOneField(
                        help_text="Original raw feedback",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_feedback",
                        to="data_ingestion.rawfeed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processed Feedback",
                "verbose_name_plural": "Processed Feedbacks",
                "ordering": ["-processed_at"],
                "indexes": [
                    models.Index(
                        fields=["sentiment", "processed_at"],
                        name="analysis_pr_sentime_a27613_idx",
                    ),
                    models.Index(
                        fields=["urgency", "processed_at"],
                        name="analysis_pr_urgency_08cd76_idx",
                    ),
                    models.Index(
                        fields=["sentiment_score"],
                        name="analysis_pr_sentime_bc2c5f_idx",
                    ),
                ],
            },
        ),
    ]
