# Generated by Django 5.0.6 on 2026-01-02 07:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who created this entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Business Entities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=20)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("twitter", "Twitter"),
                            ("reddit", "Reddit"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("app_store", "App Store"),
                            ("play_store", "Play Store"),
                            ("email", "Email"),
                            ("csv", "CSV Upload"),
                            ("api", "API"),
                            ("other", "Other"),
                        ],
                        default="csv",
                        max_length=50,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("successful_rows", models.IntegerField(default=0)),
                ("failed_rows", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                (
                    "error_log",
                    models.JSONField(
                        default=list,
                        help_text="List of errors encountered during processing",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="data_ingestion.businessentity",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Batch",
                "verbose_name_plural": "Feedback Batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RawFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="Raw feedback text")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("twitter", "Twitter"),
                            ("reddit", "Reddit"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("app_store", "App Store"),
                            ("play_store", "Play Store"),
                            ("email", "Email"),
                            ("csv", "CSV Upload"),
                            ("api", "API"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="Product being reviewed",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of customer who gave feedback",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Customer email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Rating from 1 to 5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="External reference ID from source system",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if processing failed",
                        null=True,
                    ),
                ),
                (
                    "feedback_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Original date when feedback was given",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When record was created in our system",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When feedback was successfully processed",
                        null=True,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_feeds",
                        to="data_ingestion.businessentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Feedback",
                "verbose_name_plural": "Raw Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="businessentity",
            index=models.Index(
                fields=["owner", "is_active"], name="data_ingest_owner_i_a70480_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawfeed",
            index=models.Index(
                fields=["entity", "status"], name="data_ingest_entity__e6fd21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawfeed",
            index=models.Index(
                fields=["source", "created_at"], name="data_ingest_source_116c2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawfeed",
            index=models.Index(
                fields=["status", "created_at"], name="data_ingest_status_a5249b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawfeed",
            index=models.Index(
                fields=["product_name"], name="data_ingest_product_be786f_idx"
            ),
        ),
    ]
