# Generated by Django 5.0.6 on 2026-01-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfeed',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash of text for deduplication', max_length=64, null=True),
        ),
    ]
