# Generated by Django 5.0.6 on 2026-01-05 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0002_rawfeed_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfeed',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The batch this feedback belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_feedbacks', to='data_ingestion.feedbackbatch'),
        ),
    ]
